include: package:lint/analysis_options.yaml

linter:
  rules:
    prefer_single_quotes: true
    avoid_classes_with_only_static_members: false

analyzer:
  exclude: 
    - '**/*.freezed.dart'
    - '**/*.g.dart'
    - lib/**/*.*.dart
    - lib/generated/intl/*
    - '**/mocks.mocks.dart'
    - '**/shiori_icons.dart'
  errors:
    missing_return: error