targets:
  $default:
    builders:
      hive_generator:
        generate_for:
          - lib/domain/models/entities/**
      envied_generator:envied:
        generate_for:
          - lib/env.dart
      json_serializable:
        generate_for:
          - lib/domain/models/**
      freezed:
        generate_for:
          - lib/application/**
          - lib/domain/models/**
      mockito:mockBuilder:
        generate_for:
          - test/mocks.dart