name: shiori
description: A Database app.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.6.13+127

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  darq: ^2.0.0
  device_info_plus: ^9.0.3
  devicelocale: ^0.6.0
  enum_to_string: ^2.0.1
  envied: ^0.3.0+3
  file_picker: ^5.3.3
  fk_user_agent: ^2.1.0
  fl_chart: ^0.63.0
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.1
  flutter_colorpicker: ^1.0.3
  flutter_inappwebview: ^5.7.2+3
  flutter_local_notifications: ^15.1.0+1
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.17+1
  flutter_native_timezone: ^2.0.0
  flutter_slidable: ^3.0.0
  fluttertoast: ^8.2.2
  freezed_annotation: ^2.2.0
  get_it: ^7.6.0
  grouped_list: ^5.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  html: ^0.15.4
  http: ^1.1.0
  image_gallery_saver: ^2.0.3
  infinite_listview: ^1.1.0
  internet_connection_checker: ^1.0.0+1
  intl: ^0.18.1
  json_annotation: ^4.7.0
  linked_scroll_controller: ^0.2.0
  logger: ^2.0.1
  package_info_plus: ^4.1.0
  path: ^1.8.3
  path_provider: ^2.1.0
  permission_handler: ^10.4.3
  pull_to_refresh: ^2.0.0
  purchases_flutter: ^5.6.2
  rate_my_app: ^2.0.0
  responsive_builder: ^0.7.0
  responsive_grid: ^2.4.2
  screenshot: ^2.1.0
  share_plus: ^7.1.0
  shared_preferences: ^2.2.0
  sprintf: ^7.0.0
  store_checker: ^1.3.0
  synchronized: ^3.1.0
  transparent_image: ^2.0.1
  url_launcher: ^6.1.12
  version: ^3.0.0
  #This is until my pr gets merged
  version_tracker:
    git:
      url: https://github.com/Wolfteam/version_tracker
      ref: 1af9d7297f050a5c2d5101ef444197f8fca1e921
  wakelock_plus: ^1.1.1
  waterfall_flow: ^3.0.2
  webview_windows: 0.3.0
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding
      path: plugins/window_size

dev_dependencies:
  bloc_test: ^8.5.0
  build_runner:
  envied_generator: ^0.3.0+3
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  freezed: ^2.2.1
  hive_generator: ^2.0.1
  intl_utils: ^2.8.4
  json_serializable: ^6.5.4
  lint: ^2.1.2
  mockito: ^5.4.2
  msix: ^3.16.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  image_path_ios: "assets/icon/icon_ios.png"
  remove_alpha_ios: true
  macos:
    generate: true
    image_path: "assets/icon/icon_macos.png"

flutter:
  uses-material-design: true

  assets:
    - assets/elements/
    - assets/others/
    - assets/weapon_types/
    - assets/icon/icon.png

  fonts:
    - family: Shiori
      fonts:
        - asset: assets/fonts/Shiori.ttf

flutter_intl:
  enabled: true

msix_config:
  display_name: "Shiori for Genshin: Unofficial"
  publisher_display_name: MiraiSoft
  identity_name: 52493MiraiSoft.ShioriforGenshinUnofficial
  publisher: CN=58BF90DC-3D34-433E-A12B-4C504DF78641
  logo_path: assets\icon\icon.png
  languages: en
  capabilities: 'internetClient'
  store: true
